-- ═══════════════════════════════════════════════════════════════════════════
--  ETHYRIAL ADDON API  —  WHITELISTED API INDEX
--  Version: 1.0
-- ═══════════════════════════════════════════════════════════════════════════
--
--  This directory contains the complete whitelisted Lua API available to
--  addon developers. Organized by category — like World of Warcraft's
--  addon API — each file documents one domain with full function signatures.
--
--  IMPORTANT: This is a READ + DISPLAY only API. Addons cannot perform
--  game actions (casting, moving, gathering, targeting, teleporting, etc.).
--  Like WoW addons, you may only read game state and display information.
--
--  ┌────────────────────────────────────────────────────────────────────┐
--  │  300+ Functions  •  20+ Namespaces  •  17 Category Files         │
--  └────────────────────────────────────────────────────────────────────┘
--
-- ═══════════════════════════════════════════════════════════════════════════
--  FILE INDEX
-- ═══════════════════════════════════════════════════════════════════════════
--
--  ── CHARACTER ────────────────────────────────────────────────────────
--  Player.lua        core.player.*           Health, mana, stats, buffs,
--                                            class, armor, position
--
--  Movement.lua      (REMOVED)               Movement functions are not
--                                            available to addon API
--
--  Camera.lua        core.camera.*           Read zoom, angle, pitch,
--                                            distance limits
--
--  Pets.lua          core.pets.*             Companions, attack speed,
--                                            pet commands
--
--  ── COMBAT ──────────────────────────────────────────────────────────
--  Combat.lua        core.spells.*           Cooldowns, spell info,
--                    core.spell_book.*       spell book data, spell dump,
--                    core.rotation.*         class rotation data (READ)
--
--  Targeting.lua     core.targeting.*        Read target info, HP,
--                                            enemy scan, cast detect
--
--  Buffs.lua         core.buff_manager.*     Buff/debuff queries,
--                    buff_tracker module      stacks, durations, tracking
--
--  Events.lua        core.register_on_*()   Callbacks for combat enter/
--                    combat_tracker module    leave, spell cast, damage,
--                    combat_stats module      buff changes, target change,
--                                            session performance stats
--
--  ── ITEMS & ECONOMY ─────────────────────────────────────────────────
--  Inventory.lua     core.inventory.*        Read bag items, equipment,
--                    core.loot.*             loot info, roll windows,
--                    core.loot_roll.*        item database queries,
--                    core.item_db.*          potion lookups (READ)
--
--  ── WORLD ───────────────────────────────────────────────────────────
--  World.lua         core.world.*            Scene entities, quests,
--                    core.entities.*         MonsterDex, entity scan,
--                    core.object_manager.*   OOP player/target proxies
--
--  Gathering.lua     core.gathering.*        Read node locations, herbs,
--                                            trees, ores, water (READ)
--
--  Terrain.lua       core.terrain.*          Raycasting, walkability,
--                    core.floor.*            terrain grid, floor items
--
--  ── SOCIAL ──────────────────────────────────────────────────────────
--  Social.lua        core.social.*           Chat, party, nearby players,
--                    core.guild.*            guild info/members,
--                    core.matchmaking.*      PvP matchmaking
--
--  ── UI & DISPLAY ────────────────────────────────────────────────────
--  UI.lua            game.ui.*               Unity Canvas panels, text,
--                                            bars, drag-to-move
--
--  EthyUI.lua        (OOP wrapper)           Frame/Text/Bar classes,
--                                            profile save/load, destroy
--
--  Menu.lua          core.menu.*             ImGui settings widgets,
--                    core.imgui.*            keybinds, sliders, custom
--                                            floating windows
--
--  Drawing.lua       core.graphics.*         2D/3D overlay drawing,
--                    core.draw.*             ground shapes, ground mesh,
--                    Argus2 module            timed telegraphs, entity
--                    ShapeDrawer module       shape attachments
--
--  Notifications.lua notify.*                Overlay toasts, in-game
--                                            Unity toasts, alerts
--
--  ── SYSTEM ──────────────────────────────────────────────────────────
--  Core.lua          core.log/time           Logging, profile storage,
--                    core.game_time.*        clock, zones, station scan,
--                    zone module             zone detection, game time
--                    core.stations.*         (READ-ONLY, no actions)
--                    core.teleport.*
--                    core.network.*
--                    core.ui.messagebox_*
--
--  Enums.lua         ethy.*                  Job IDs, spell categories,
--                                            buff types, entity types,
--                                            combat states, group roles
--
-- ═══════════════════════════════════════════════════════════════════════════
--  GETTING STARTED
-- ═══════════════════════════════════════════════════════════════════════════
--
--  1. Create your addon folder under dist/plugins/<addon_name>/
--  2. Create toc.lua (addon metadata) and main.lua (entry point)
--  3. Use core.register_on_*_callback() to hook into game events
--  4. Reference the API files above for available functions
--
--  Example addon (main.lua):
--
--    -- Display a healing reminder when HP is low
--    core.register_on_render_callback(function()
--        local hp  = core.player.hp()
--        local max = core.player.max_hp()
--        if hp < max * 0.5 then
--            core.graphics.set_camera()
--            local pos = core.player.get_position()
--            core.graphics.text_3d(pos.x, pos.y + 2, pos.z,
--                "!! HEAL !!",
--                core.graphics.color(255, 0, 0, 255), 20)
--        end
--    end)
--
--    -- Show cooldown tracker in settings
--    core.register_on_render_menu_callback(function()
--        local show = core.menu.checkbox("Show CD Tracker", true)
--    end)
--
-- ═══════════════════════════════════════════════════════════════════════════
